SF_CodeBase/objects/Assignment_Group_Name__c.object
<CustomObject>
</CustomObject>

SF_CodeBase/objects/Assignment_Group_Queues__c.object
<CustomObject>
</CustomObject>

SF_CodeBase/objects/Assignment_Groups__c.object
<CustomObject>
    <description>Used to assign ownership of records users via Apex</description>
    <fields>
        <fullName>Active__c</fullName>
        <description>If True, then include user in Round Robin assignments.</description>
        <inlineHelpText>If False, then include user in Round Robin assignments.</inlineHelpText>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>True</fullName>
                    <default>true</default>
                    <label>True</label>
                </value>
                <value>
                    <fullName>False</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <referenceTo>Assignment_Group_Name__c</referenceTo>
        <relationshipName>Assignment_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Assignment__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>Last time case was assigned to this person</description>
        <inlineHelpText>Last time case was assigned to this person</inlineHelpText>
        <label>Last Assignment</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N30000002Yj6ZEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Group Member</label>
    <nameField>
        <displayFormat>AG-{0000}</displayFormat>
        <label>Assignment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SF_CodeBase/objects/Trigger_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Created this to enable/disable triggers.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Settings</label>
</CustomObject>

SF_CodeBase/classes/Test_LeadRoundRobin.cls
@isTest()
private class Test_LeadRoundRobin {

    static testMethod void myTest2() {
        
        System.runAs(new User(Id = Userinfo.getUserId())){
        Trigger_Settings__c cs = new Trigger_Settings__c();
        cs.Name='LeadTrigger';
        cs.Is_Active__c = true;
        insert cs;
        }
        
        // This code runs as the system user
        
        User u1;
        
        try{
            u1 = [select Id from User WHERE IsActive=True AND Profile.Name = 'System Administrator'  LIMIT 1];
        } catch (QueryException qe){
            List<User> users = [SELECT Id, Profile.PermissionsModifyAllData FROM User WHERE IsActive = true LIMIT 1000];
            for(User u : users){
                if(u.Profile.PermissionsModifyAllData = true){
                    u1 = u;
                    break;
                }
            }
        }
        
        System.debug(u1);
        
        //*****Create Queue 
        
        Group testGroup = new Group ();
        testGroup.Name = 'TestQueue';
        testGroup.Type = 'Queue';
        insert testGroup;
        
        QueueSObject testQueue = new QueueSObject();
        testQueue.QueueId = testGroup.id;
        testQueue.SObjectType = 'Lead';
        insert testQueue;
        
        // Second Queue       
        Group testGroup2 = new Group ();
        testGroup2.Name = 'TestQueue2';
        testGroup2.Type = 'Queue';
        insert testGroup2;
        
        QueueSObject testQueue2 = new QueueSObject();
        testQueue2.QueueId = testGroup2.id;
        testQueue2.SObjectType = 'Lead';
        insert testQueue2;
        
        System.runAs ( u1 ) {
            test.starttest();
            
            u1.Assignment_Group_Active__c = true;
            update u1;
            
            //Run test
            
            //Create Assignment Group
            Assignment_Group_Name__c ag1 = new Assignment_Group_Name__c (Name='TestAG', Type__c = 'Lead');
            insert ag1;        
            
            //Add Good Queue to Assignment Group
            Assignment_Group_Queues__c agq1 = new Assignment_Group_Queues__c(name=testGroup.Name ,Assignment_Group_Name__c = ag1.id );
            insert agq1;
            
            //Add User to Assignment Groups Users
            Assignment_Groups__c agu1 = new Assignment_Groups__c (User__c = u1.id, Active__c='True', Group_Name__c = ag1.id, Last_Assignment__c = datetime.valueOf('2009-01-01 21:13:24') );
            insert agu1;
            
            Lead c2 = new Lead (lastName='testLead1', company='self', tempOwnerID__c=testGroup2.id , OwnerID=testGroup.id); //Set owner ID to Queue
            insert c2;
            update c2;        
            
            Lead c3 = new Lead (lastName='testLead2', company='self', tempOwnerID__c=testGroup2.id , OwnerID=testGroup.id); //Set owner ID to Queue
            insert c3;
            update c3;        

            test.stoptest();
        }
    }

}